### ISSUE TITLE
Use .env's for secrets

### ISSUE THREAD

**Issue by Silver-Golden** [Third-Floor-CSIS/cs4337-Big-Data-Group#18]
Currently in #15 the secrets are in plain text format.  
Goal of this issue is to use a library to allow use of a ``.env`` (and ``.env.development``/``.env.production``) to ensure that we do not commit secrets to the repo.

**Comment by M-Byte480** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create .env](https://trello.com/c/rJ6rzzpm/37-create-env)
