### ISSUE TITLE
Lint pipeline

### ISSUE THREAD

**Issue by M-Byte480** [Third-Floor-CSIS/cs4337-Big-Data-Group#3]

**Comment by Bourkupine** [comment]
**As a developer**
**I want to**, setup a linter for the repo
**So that** we can have a uniform coding style

**Comment by Bourkupine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Lint Pipeline](https://trello.com/c/7Nh3QhXY/2-lint-pipeline)
